### ISSUE TITLE
Rust crates should show license

### ISSUE THREAD

**Issue by lukekim** [spiceai/docs#132]
<img width="868" alt="image" src="https://github.com/spiceai/docs/assets/80174/448ef5e1-d584-4713-9e73-0bb7d1f091fe">

**Comment by ewgenius** [comment]
Fixed in #137 

https://spiceai-docs-git-evgenii-update-acknowledgments-fo-73d3fc-spice.vercel.app/acknowledgements

![CleanShot 2024-03-27 at 10 47 51@2x](https://github.com/spiceai/docs/assets/827338/528d42f4-5128-48dd-bdca-2a57aa9c1a8e)
