### ISSUE TITLE
Document refresh max jitter

### ISSUE THREAD

**Issue by peasee** [spiceai/docs#549]
Refresh API option `refresh_jitter_max` is not documented. It should be documented.

**Comment by sgrebnov** [comment]
Documentation is available, added PR to enhance existing version: 
https://github.com/spiceai/docs/pull/653

https://docs.spiceai.org/components/data-accelerators/data-refresh#refresh-jitter
![Image](https://github.com/user-attachments/assets/a04711f3-e97d-4b45-a022-bb3787a7ba62)


https://docs.spiceai.org/reference/spicepod/datasets#accelerationrefresh_jitter_max
![Image](https://github.com/user-attachments/assets/1fcde978-430d-4d6d-995b-b66ddac6a790)
